// File generated by the `firebase init` command.
// This file should be replaced with the actual file generated by Firebase CLI
// Run: firebase init and then run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCokZfFDNAjkHIwsz1UkXfvz3spOTXS-H0',
    appId: '1:616817065201:web:214a851622c62a6220bd50',
    messagingSenderId: '616817065201',
    projectId: 'eforward-app',
    authDomain: 'eforward-app.firebaseapp.com',
    storageBucket: 'eforward-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC7AlyOm3jHSampvY0QYTuBlfqHEhyVnk',
    appId: '1:616817065201:android:43eec7349231241220bd50',
    messagingSenderId: '616817065201',
    projectId: 'eforward-app',
    storageBucket: 'eforward-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaHdnDl6QXuWVtqLjuTO7zrcmgYiUY5oU',
    appId: '1:616817065201:ios:28474eeabc93674120bd50',
    messagingSenderId: '616817065201',
    projectId: 'eforward-app',
    storageBucket: 'eforward-app.firebasestorage.app',
    iosBundleId: 'com.example.eforwardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaHdnDl6QXuWVtqLjuTO7zrcmgYiUY5oU',
    appId: '1:616817065201:ios:28474eeabc93674120bd50',
    messagingSenderId: '616817065201',
    projectId: 'eforward-app',
    storageBucket: 'eforward-app.firebasestorage.app',
    iosBundleId: 'com.example.eforwardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCokZfFDNAjkHIwsz1UkXfvz3spOTXS-H0',
    appId: '1:616817065201:web:051cc64e636b92f720bd50',
    messagingSenderId: '616817065201',
    projectId: 'eforward-app',
    authDomain: 'eforward-app.firebaseapp.com',
    storageBucket: 'eforward-app.firebasestorage.app',
  );

}